project_id = "gymcneistfprympxrybr"

[functions.verify-admin]
verify_jwt = false

[functions.admin-clues]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.submit-answer]
verify_jwt = false