project_id = "gymcneistfprympxrybr"

[functions.verify-admin]
verify_jwt = false

[functions.admin-secrets]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.submit-guess]
verify_jwt = false
